// Generated by scripts/prepare-content.mjs
export default {
  "louis-vincent/wall-panel-i": {
    "title": "Wall Panel 1",
    "artist": "Louis Vincent",
    "path": "/gallery/louis-vincent/wall-panel-i/"
  },
  "louis-vincent/plate": {
    "title": "Plate",
    "artist": "Louis Vincent",
    "path": "/gallery/louis-vincent/plate/"
  },
  "louis-vincent/conical-bowl": {
    "title": "Conical Bowl",
    "artist": "Louis Vincent",
    "path": "/gallery/louis-vincent/conical-bowl/"
  },
  "louis-vincent/bowl": {
    "title": "Bowl",
    "artist": "Louis Vincent",
    "path": "/gallery/louis-vincent/bowl/"
  },
  "louis-vincent/wall-panel-ii": {
    "title": "Wall Panel 2",
    "artist": "Louis Vincent",
    "path": "/gallery/louis-vincent/wall-panel-ii/"
  },
  "jihyun-kim/teoju": {
    "title": "Teoju #1",
    "artist": "Jihyun Kim",
    "path": "/gallery/jihyun-kim/teoju/"
  },
  "jihyun-kim/small-teoju": {
    "title": "Small Teoju",
    "artist": "Jihyun Kim",
    "path": "/gallery/jihyun-kim/small-teoju/"
  },
  "jacob-chan/chess-set": {
    "title": "Chess Set",
    "artist": "Jacob Chan",
    "path": "/gallery/jacob-chan/chess-set/"
  },
  "jacob-chan/sake-set": {
    "title": "Sake Set",
    "artist": "Jacob Chan",
    "path": "/gallery/jacob-chan/sake-set/"
  },
  "jacob-chan/ginger-jar-2": {
    "title": "Ginger Jar",
    "artist": "Jacob Chan",
    "path": "/gallery/jacob-chan/ginger-jar-2/"
  },
  "jacob-chan/sake-bottle": {
    "title": "Sake Bottle",
    "artist": "Jacob Chan",
    "path": "/gallery/jacob-chan/sake-bottle/"
  },
  "jacob-chan/ginger-jar": {
    "title": "Ginger Jar",
    "artist": "Jacob Chan",
    "path": "/gallery/jacob-chan/ginger-jar/"
  },
  "jacob-chan/sake-bottle-2": {
    "title": "Sake Bottle",
    "artist": "Jacob Chan",
    "path": "/gallery/jacob-chan/sake-bottle-2/"
  },
  "alexandra-yan-wong/untitled-2025": {
    "title": "Untitled, 2025",
    "artist": "Alexandra Yan Wong",
    "path": "/gallery/alexandra-yan-wong/untitled-2025/"
  },
  "adam-weismann/clay-2025": {
    "title": "Clay 1666",
    "artist": "Adam Weismann",
    "path": "/gallery/adam-weismann/clay-2025/"
  },
  "arran-gregory/the-universe-was-an-egg-which-cracked": {
    "title": "The Universe Was AN Egg Which Cracked",
    "artist": "Arran Gregory",
    "path": "/gallery/arran-gregory/the-universe-was-an-egg-which-cracked/"
  },
  "arran-gregory/heart-of-matter": {
    "title": "Heart of Matter",
    "artist": "Arran Gregory",
    "path": "/gallery/arran-gregory/heart-of-matter/"
  },
  "zahed-tajeddin/bulls-matter": {
    "title": "Bull's Matter",
    "artist": "Zahed Tajeddin",
    "path": "/gallery/zahed-tajeddin/bulls-matter/"
  },
  "zahed-tajeddin/bowing-bull": {
    "title": "Bowing Bull",
    "artist": "Zahed Tajeddin",
    "path": "/gallery/zahed-tajeddin/bowing-bull/"
  },
  "zahed-tajeddin/elevation": {
    "title": "Elevation",
    "artist": "Zahed Tajeddin",
    "path": "/gallery/zahed-tajeddin/elevation/"
  },
  "zahed-tajeddin/stillness": {
    "title": "Stillness",
    "artist": "Zahed Tajeddin",
    "path": "/gallery/zahed-tajeddin/stillness/"
  },
  "rickie-cheuk/chopsticks": {
    "title": "Chopsticks",
    "artist": "Rickie Cheuk",
    "path": "/gallery/rickie-cheuk/chopsticks/"
  }
} as const;
